### PR TITLE
first pass edits on full manuscript

### PR DESCRIPTION
**Pull request by lauterbur**
This is more or less the full document, needs a few minor things here and there (see README), maybe some expansions in certain places.

### CODE REVIEW

**Comment by lauterbur** [comment]
@andrewkern What's the best way to do the Latex conversion, merge this first?

**Comment by andrewkern** [comment]
sure yeah-- let's merge this and then i can work on a PR moving it to latex

**Comment by andrewkern** [comment]
hey @lauterbur -- i see you merged this, awesome! any chance you forgot to commit changes to the main doc here? i only see edits to the new supplemental bits

**Comment by lauterbur** [comment]
Um, apparently. Should be good now.

**Comment by andrewkern** [comment]
okay-- i think you'll need to submit another PR for us to merge into main

**Comment by lauterbur** [comment]
I just pushed everything again, and I see the most recent changes in the files on the main branch, including my silly commit message. Has that fixed things for you?

**Pull request merged**
