### PR TITLE
Ilan's restructuring of first part of results

### PR DESCRIPTION
**Pull request by igronau**
Section 1: Standardized genome-wide simulations

New section structure and additional minor edits.
Sections 3-5 still require significant edits

### CODE REVIEW

**Comment by petrelharp** [comment]
Hi, @igronau - this looks good. what's the status of it? Do you want review on this now? Should we merge it? You said on slack you've got more major edits to do?

**Comment by igronau** [comment]
I won't have time to edit until mid next week (at least), and I'd like to get some feedback on the first part (Standardized genome-wide simulations). So it probably makes sense to merge this and allow people to provide feedback on this section. Especially the part about simulating whole chromosomes, which I significantly shortened.

**Comment by lauterbur** [comment]
Thanks, Ilan. I'll merge (unless someone else gets to it first) and give it
a look this weekend.

**Comment by lauterbur** [comment]
@igronau How would you prefer feedback on this step of your edts, this PR (now merged), slack, a new PR?

**Pull request merged**
