### PR TITLE
Update adding_species_manuscript.tex for BosTau Ne

### PR DESCRIPTION
**Pull request by gregorgorjanc**
Updating description regarding the effective population size in the basic genome model and the demographic model.

@gtsambos and @petrelharp I would appreciate your revision of this change so that we are all on the same page.

Thanks!

### CODE REVIEW

**Comment by petrelharp** [comment]
I like it - no complaints.

**Comment by igronau** [comment]
Looks good to me. @lauterbur - can you merge?

**Comment by lauterbur** [comment]
With pleasure.

**Comment by gtsambos** [comment]
Sorry for the late reply all -- I had limited access to laptop internet while I was in CZ. This looks good to me, thanks for doing it @gregorgorjanc!

**Pull request merged**
