### PR TITLE
Changes from Ryan

### PR DESCRIPTION
**Pull request by RyanGutenkunst**
Generally pretty minor changes. Most significantly, I added DFE references, cleaned up my TODO, removed some technical details about selection.

### CODE REVIEW

**Review by igronau — APPROVED** [review]
Looks good. I'll tick off the relevant tasks. This is ready to merge @lauterbur should be next, I think

**Review by andrewkern — APPROVED** [review]
looks good to me

**Comment by andrewkern** [comment]
@lauterbur -- you've got the ball

**Comment by lauterbur** [comment]
Thanks! Gives me something to do on my flights on Sunday.

**Pull request merged**
