### PR TITLE
Adk pass 

### PR DESCRIPTION
**Pull request by andrewkern**
Opening this as a draft PR because I'd like to get some feedback on my reorganization of the paper up to the "Updates to `stdpopsim`" section.

In reading through where the paper was at, I was unhappy with how we were trying to straddle this being about stdpopsim vs a general guide to simulation. I've tried to be a bit bolder in this intro reorganization to move the paper **more** towards being about stdpopsim.

@gphocs-dev @lauterbur @dschride @petrelharp @jeromekelleher, others-- what do you think of what I've done so far here to the tone? i'm going to keep going but could use some feedback I think

### CODE REVIEW

**Comment by gregorgorjanc** [comment]
@andrewkern @gphocs-dev I have checked out this PR and revised the Bos Taurus section. How do I push my changes? 

```
ggorjanc@S37-81T5G3QP adding-species-manuscript-mine % gh pr checkout 49
? Which should be the base repository (used for e.g. querying issues) for this directory? popsim-consortium/adding-species-manuscript
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 30 (delta 17), reused 25 (delta 12), pack-reused 0
Unpacking objects: 100% (30/30), 57.78 KiB | 71.00 KiB/s, done.
From https://github.com/popsim-consortium/adding-species-manuscript
 * [new ref]         refs/pull/49/head -> adk_pass
Switched to branch 'adk_pass'
ggorjanc@S37-81T5G3QP adding-species-manuscript-mine % git add adding-species-manuscript.Rproj 
ggorjanc@S37-81T5G3QP adding-species-manuscript-mine % git add references.bib 
ggorjanc@S37-81T5G3QP adding-species-manuscript-mine % git commit -m "Reviewing Bos Taurus changes"                     
[adk_pass 4d7ad7d] Reviewing Bos Taurus changes
 2 files changed, 877 insertions(+), 850 deletions(-)
 create mode 100644 adding-species-manuscript.Rproj
ggorjanc@S37-81T5G3QP adding-species-manuscript-mine % git push
remote: Permission to andrewkern/adding-species-manuscript.git denied to gregorgorjanc.
fatal: unable to access 'https://github.com/andrewkern/adding-species-manuscript.git/': The requested URL returned error: 403
```

**Comment by andrewkern** [comment]
@gregorgorjanc -- you could open a PR with your changes against the `main` branch of the popsim-consortium repo-- i haven't yet edited the Bos section

**Comment by andrewkern** [comment]
alternatively you could open a PR against my branch and I could incorporate there, but I think it's cleaner for you to open your PR against main

**Comment by gregorgorjanc** [comment]
@andrewkern you made some changes hence I pulled your PR, but I am not clear how a make a PR against your PR?

**Comment by andrewkern** [comment]
submit a PR against this branch: https://github.com/andrewkern/adding-species-manuscript/tree/adk_pass

**Comment by igronau** [comment]
I'm going to spend much of the next few days in transition, but I'll try to take some time to review when I get a chance

**Comment by andrewkern** [comment]
Okay and meanwhile I will keep going through the doc on my editing pass.

**Comment by lauterbur** [comment]
I will take a look this evening or (more likely) tomorrow. We have had a lot of back and forth about which side of the general guidelines/stdpopsim specific line this belongs on, hence the current straddling. I think it would be a good idea to make a final decision on that before doing too much more restructuring, because we have already gone from one side to the other and back again.

**Comment by andrewkern** [comment]
okay so at this point I've gone once through the doc and taken care of most (all?) of @gphocs-dev's queries. 

@dschride sent me some comments via email that i will incorporate next to this PR but they are mostly small. Once those are in I will squash.

**Comment by andrewkern** [comment]
Okay this is ready for review / merge / etc

**Review by igronau — APPROVED** [review]
I think that this can be merged in as is. I do have a few questions and comments:

1. The paragraph titles in the first section (after the intro): do you mean to keep those? It is a bit bold (stdpopsim fixes this ;-)). Can't we drive these points without the titles?
2. In the "genomic architecture" paragraph in that section, there is a rough transition between the first short paragraph and the following long paragraph. There' a missing period, and also there appears to be a statement missing between the two lines of argument.
3. The part about allowing demographic models in stdpopsim to have their own mutation rate. I know it's a very low-level feature, but it is important when trying to use a demographic model inferred with an outdated mutation rate, which is the scenario we discuss in that paragraph. We also mention this later in the Bos Taurus example, which Is why I thought it made sense to mention this feature earlier. It makes sense for this to be in the 'guidelines' section. However, maybe there is a better way to mention it here.
4. In the mosquito example, the second sentence is a bit unclear and leads to a rough transition into the next one.
5. There are a few highlighted TODOs directed to you that you can remove.

**Comment by andrewkern** [comment]
Okay thanks @igronau. I will merge this PR. 

@dschride I believe the ball is now yours.

**Pull request merged**
